notifications:
  email: false

language: python
python:
  - "3.8"

os: linux
dist: xenial

before_install:
  - pip install codecov

install:
    pip install -r requirements.txt

script:
    - python -m pytest -v

after_success:
    - python benchmark/bench_generator.py
    - codecov
