notifications:
  email: false

language: python
python:
  - "3.6"

sudo: required
dist: trusty

before_install:
  - pip install codecov

install:
    pip install -r requirements.txt

script:
    - python -m pytest -v

after_success:
    - codecov
