language: python

env:
  - CODECOV_TOKEN=

jobs:
  include:
    - name: "Python 3.7 on Xenial Linux"
      os: linux
      python: 3.7
      script:
        - python -m pytest -v
      after_success:
        - codecov
